const {test}=require('node:test');
const assert=require('node:assert/strict');
const C=require('./core.js');
test('CSV round-trip preserves commas, quotes, newlines and BOM',()=>{const rows=[{date:'2026-09-01',product:'a,"b"\nc',quantity:3}];assert.deepEqual(C.parseCSV(C.csv(rows)).rows,[{...rows[0],quantity:'3'}]);assert.throws(()=>C.parseCSV('a,b\n"x,y'),/따옴표/);assert.throws(()=>C.parseCSV('a,a\n1,2'),/중복/)});
test('mapped imports reject impossible dates, duplicate keys and missing days',()=>{const rows=C.sampleRows();assert.equal(C.normalize(rows,C.mapping).length,252);const invalid=C.clone(rows);invalid[0].date='2026-02-30';assert.throws(()=>C.normalize(invalid,C.mapping),/날짜/);assert.throws(()=>C.normalize([...rows,rows[0]],C.mapping),/중복/);assert.throws(()=>C.normalize(rows.filter((_,i)=>i!==12),C.mapping),/누락|최소/)});
test('graph rejects incompatible order and duplicate transforms',()=>{const state=C.seed(),c=C.clone(state.compositions[0]);assert.deepEqual(C.validate(c),[]);[c.nodes[1],c.nodes[2]]=[c.nodes[2],c.nodes[1]];assert.ok(C.validate(c).length);c.nodes=['read','normalize','smooth','smooth','forecast','export'];assert.ok(C.validate(c).length)});
test('run creates linked output and stable provenance without modifying input',()=>{const s=C.seed(),c=s.compositions[0],source=JSON.stringify(s.artifacts.find(a=>a.kind==='input'));const prior=C.clone(s.runs[0]);const a=C.execute(s,c,{model:'last',horizon:7,range:'28'});assert.equal(a.rows.length,21);assert.equal(s.runs[0].output,a.id);assert.ok(s.entities.find(e=>e.comp===c.id).artifacts.includes(a.id));assert.equal(JSON.stringify(s.artifacts.find(a=>a.kind==='input')),source);c.params.horizon=28;c.nodes.splice(2,0,'smooth');assert.deepEqual(s.runs[1],prior);assert.equal(s.runs[0].params.horizon,7);assert.equal(s.runs[0].nodes.length,4)});
test('seasonal baseline repeats the final week; last-value and smoothing affect output',()=>{const s=C.seed(),c=s.compositions[0];const normalized=C.normalize(C.sampleRows(),C.mapping),lastWeek=normalized.filter(r=>r.series_id==='아메리카노').slice(-7);const a=C.execute(s,c,{model:'seasonal',horizon:14,range:'all'});assert.deepEqual(a.rows.slice(0,14).map(r=>r.forecast_value),[...lastWeek,...lastWeek].map(r=>r.value));c.nodes.splice(2,0,'smooth');const b=C.execute(s,c,{model:'last',horizon:7,range:'all'});assert.equal(b.rows[0].forecast_value,Math.round(lastWeek.reduce((v,r)=>v+r.value,0)/7))});
test('publishing freezes a versioned design artifact',()=>{const s=C.seed(),c=s.compositions[0],a=C.publish(s,c);c.name='changed';c.nodes.pop();assert.notEqual(a.snapshot.name,c.name);assert.equal(a.snapshot.nodes.length,4);assert.equal(a.snapshot.version,2)});
test('failed execution never registers partial artifacts',()=>{const s=C.seed(),c=s.compositions[0],before=JSON.stringify(s);assert.throws(()=>C.execute(s,c,{horizon:999,model:'last',range:'all'}));assert.equal(JSON.stringify(s),before);c.nodes.reverse();const n=s.artifacts.length;assert.throws(()=>C.execute(s,c,c.params));assert.equal(s.artifacts.length,n)});

test('aligned series prevent misleading aggregate forecast dates',()=>{assert.throws(()=>C.normalize(C.sampleRows().slice(0,-1),C.mapping),/마지막 날짜/)});
